### ISSUE TITLE
PlanetScaleの無料枠がなくなったので別のものに置き換える

### ISSUE THREAD

**Issue by wheatandcat** [wheatandcat/stock-keeper-backend#3]
# メモ
 - [無料枠が無くなったPlanetScale の代替DBを検討する。 #MySQL - Qiita](https://qiita.com/Kenta_Kobayashi/items/ba445245ecd357dd19d7)
 - [Prismaを使っている開発中プロダクトをPlanetScaleからNeonへ移行する](https://sendo-blog.com/article/planetscale-to-neon-config)
 - [Nest.js REST API with Prisma ORM, Neon Postgres - YouTube](https://www.youtube.com/watch?v=6He5Gyuuvxk)

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.

**Comment by wheatandcat** [comment]
oh! Thank you! I think to try TiDB.
